/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/account": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateAccountDto"];
          "text/json": components["schemas"]["CreateAccountDto"];
          "application/*+json": components["schemas"]["CreateAccountDto"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          content: never;
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/v1/account/profiles": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ProfilesDto"];
            "application/json": components["schemas"]["ProfilesDto"];
            "text/json": components["schemas"]["ProfilesDto"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/v1/account/profiles/senior": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["EncodedSeniorDto"];
            "application/json": components["schemas"]["EncodedSeniorDto"];
            "text/json": components["schemas"]["EncodedSeniorDto"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    post: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ProfileDisplayDto"];
            "application/json": components["schemas"]["ProfileDisplayDto"];
            "text/json": components["schemas"]["ProfileDisplayDto"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/v1/account/profiles/caretaker": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateCaretakerProfileDto"];
          "text/json": components["schemas"]["CreateCaretakerProfileDto"];
          "application/*+json": components["schemas"]["CreateCaretakerProfileDto"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SeniorIdDto"];
            "application/json": components["schemas"]["SeniorIdDto"];
            "text/json": components["schemas"]["SeniorIdDto"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/v1/healthz": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HealthcheckDto"];
            "application/json": components["schemas"]["HealthcheckDto"];
            "text/json": components["schemas"]["HealthcheckDto"];
          };
        };
      };
    };
  };
  "/api/v1/token": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GetAccountByCredentialsDto"];
          "text/json": components["schemas"]["GetAccountByCredentialsDto"];
          "application/*+json": components["schemas"]["GetAccountByCredentialsDto"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TokenDto"];
            "application/json": components["schemas"]["TokenDto"];
            "text/json": components["schemas"]["TokenDto"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateAccountDto: {
      email: string;
      password: string;
      phoneNumber?: string | null;
      displayName: string;
    };
    CreateCaretakerProfileDto: {
      /** Format: int32 */
      hash: number;
      seniorAlias: string;
    };
    EncodedSeniorDto: {
      /** Format: int32 */
      hash: number;
      seniorDisplayName: string;
      /** Format: int32 */
      validFor: number;
    };
    GetAccountByCredentialsDto: {
      email: string;
      password: string;
    };
    HealthcheckDto: {
      server?: components["schemas"]["HealthcheckStatus"];
      database?: components["schemas"]["HealthcheckStatus"];
    };
    /** @enum {string} */
    HealthcheckStatus: "Ok" | "Unhealthy";
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      [key: string]: unknown;
    };
    ProfileDisplayDto: {
      type: string;
      /** Format: int32 */
      seniorId: number;
      seniorAlias: string;
    };
    ProfilesDto: {
      profiles: components["schemas"]["ProfileDisplayDto"][];
    };
    SeniorIdDto: {
      /** Format: int32 */
      seniorId: number;
    };
    TokenDto: {
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
