name: Build APK

on:
  workflow_dispatch:
  pull_request: # just for testing
    branches: [main]
    paths-ignore: ["**.md"]
  push:
    branches: [main]
    paths-ignore: ["**.md"]

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: "cd android && ./gradlew assembleRelease"

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
